{"uid":"dfd6ce7f5c9746c4","name":"Direct Access to Profile Page with Auth Cookie","fullName":"tests.web.admin.test_session_persistence.TestSessionPersistence#test_direct_access_with_auth_cookie","historyId":"6e3b3da886636d844a88ece1bf4af484","time":{"start":1757068146509,"stop":1757068146509,"duration":0},"description":"Verify profile page can be accessed directly with authentication cookies","descriptionHtml":"<p>Verify profile page can be accessed directly with authentication cookies</p>\n","status":"broken","statusMessage":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","statusTrace":"request = <SubRequest 'user_auth' for <Coroutine test_direct_access_with_auth_cookie>>\nkwargs = {'runner': <utils.browser_config.Config object at 0x7f6686b24610>}\nunittest = False, func = <function user_auth at 0x7f668c4e02c0>\nsetup = <function _wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.setup at 0x7f6686d5ed40>\nfinalizer = <function _wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer at 0x7f6686dcc680>\n\n    @functools.wraps(fixture)\n    def _asyncgen_fixture_wrapper(request: FixtureRequest, **kwargs: Any):\n        unittest = fixturedef.unittest if hasattr(fixturedef, \"unittest\") else False\n        func = _perhaps_rebind_fixture_func(fixture, request.instance, unittest)\n        event_loop = kwargs.pop(event_loop_fixture_id)\n        gen_obj = func(\n            **_add_kwargs(func, kwargs, event_loop_fixture_id, event_loop, request)\n        )\n    \n        async def setup():\n            res = await gen_obj.__anext__()\n            return res\n    \n        def finalizer() -> None:\n            \"\"\"Yield again, to finalize.\"\"\"\n    \n            async def async_finalizer() -> None:\n                try:\n                    await gen_obj.__anext__()\n                except StopAsyncIteration:\n                    pass\n                else:\n                    msg = \"Async generator fixture didn't stop.\"\n                    msg += \"Yield only once.\"\n                    raise ValueError(msg)\n    \n            event_loop.run_until_complete(async_finalizer())\n    \n>       result = event_loop.run_until_complete(setup())\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py:347: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py:654: in run_until_complete\n    return future.result()\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py:329: in setup\n    res = await gen_obj.__anext__()\nconftest.py:73: in user_auth\n    page_instance = await runner.setup_auth_page(\"user\")\nutils/browser_config.py:130: in setup_auth_page\n    context = await self.context_init(storage_state=True, user_type=auth_mode, device_name=device_name)\nutils/browser_config.py:107: in context_init\n    session_file = await self.session_handler.create_session(user_type)\nutils/sess_handler.py:82: in create_session\n    email, password = self.load_credentials(user_type)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <utils.sess_handler.SessionHandler object at 0x7f6686b24510>\nuser_type = 'user'\n\n    def load_credentials(self, user_type):\n        mapping = {\n            \"user\": [\"USER_EMAIL\", \"USER_PASSWORD\"],\n            \"admin\": [\"ADMIN_EMAIL\", \"ADMIN_PASSWORD\"],\n            \"super_admin\": [\"SUPER_ADMIN_EMAIL\", \"SUPER_ADMIN_PASSWORD\"]\n        }\n    \n        # Default to user type if not in mapping\n        env_vars = mapping.get(user_type.lower(), [\"USER_EMAIL\", \"USER_PASSWORD\"])\n    \n        # Get credentials from environment variables\n        email = os.getenv(env_vars[0])\n        password = os.getenv(env_vars[1])\n    \n        if email and password:\n            return email, password\n        else:\n>           raise ValueError(f\"Credentials for {user_type} not found. Set {env_vars[0]} and {env_vars[1]} in your .env file.\")\nE           ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.\n\nutils/sess_handler.py:66: ValueError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop","time":{"start":1757068146509,"stop":1757068146510,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"playwright","time":{"start":1757068146510,"stop":1757068146737,"duration":227},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"runner","time":{"start":1757068146737,"stop":1757068146821,"duration":84},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"user_auth","time":{"start":1757068146821,"stop":1757068146869,"duration":48},"status":"broken","statusMessage":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 897, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py\", line 347, in _asyncgen_fixture_wrapper\n    result = event_loop.run_until_complete(setup())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/asyncio/base_events.py\", line 654, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/pytest_asyncio/plugin.py\", line 329, in setup\n    res = await gen_obj.__anext__()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/conftest.py\", line 73, in user_auth\n    page_instance = await runner.setup_auth_page(\"user\")\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/browser_config.py\", line 130, in setup_auth_page\n    context = await self.context_init(storage_state=True, user_type=auth_mode, device_name=device_name)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/browser_config.py\", line 107, in context_init\n    session_file = await self.session_handler.create_session(user_type)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/sess_handler.py\", line 82, in create_session\n    email, password = self.load_credentials(user_type)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/noov/noov/utils/sess_handler.py\", line 66, in load_credentials\n    raise ValueError(f\"Credentials for {user_type} not found. Set {env_vars[0]} and {env_vars[1]} in your .env file.\")\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"afterStages":[{"name":"runner::finalizer","time":{"start":1757068146923,"stop":1757068146954,"duration":31},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"playwright::finalizer","time":{"start":1757068146954,"stop":1757068146960,"duration":6},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::3","time":{"start":1757068146960,"stop":1757068146960,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_close_event_loop","time":{"start":1757068146960,"stop":1757068146960,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_restore_policy","time":{"start":1757068146960,"stop":1757068146961,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1757068146961,"stop":1757068146961,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"epic","value":"Admin Portal"},{"name":"feature","value":"Authentication"},{"name":"severity","value":"critical"},{"name":"tag","value":"asyncio"},{"name":"tag","value":"ui"},{"name":"parentSuite","value":"tests.web.admin"},{"name":"suite","value":"test_session_persistence"},{"name":"subSuite","value":"TestSessionPersistence"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"6227-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.web.admin.test_session_persistence"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"critical","retries":[{"uid":"8af5926c9b0bb845","status":"broken","statusDetails":"ValueError: Credentials for user not found. Set USER_EMAIL and USER_PASSWORD in your .env file.","time":{"start":1757068143997,"stop":1757068143997,"duration":0}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":1,"unknown":0,"total":4},"items":[{"uid":"1f3266ca75b5fecb","reportUrl":"https://009MHz.github.io/noov/27//#testresult/1f3266ca75b5fecb","status":"broken","statusDetails":"ValueError: Credentials for user not found and no defaults available","time":{"start":1757065006161,"stop":1757065006161,"duration":0}},{"uid":"b60a0e23e7c5358c","reportUrl":"https://009MHz.github.io/noov/26//#testresult/b60a0e23e7c5358c","status":"broken","statusDetails":"ValueError: Credentials for user not found and no defaults available","time":{"start":1757063198704,"stop":1757063198704,"duration":0}},{"uid":"db4a5d35fe947af0","reportUrl":"https://009MHz.github.io/noov/25//#testresult/db4a5d35fe947af0","status":"passed","time":{"start":1757057771490,"stop":1757057772198,"duration":708}}]},"tags":["asyncio","ui"]},"source":"dfd6ce7f5c9746c4.json","parameterValues":[]}